"""
Nifty 100 / large-cap Indian stocks for data collection.
Yahoo Finance uses .NS suffix for NSE-listed stocks.
"""

INDIAN_STOCKS = [
    {"symbol": "RELIANCE", "yahoo_symbol": "RELIANCE.NS", "name": "Reliance Industries"},
    {"symbol": "TCS", "yahoo_symbol": "TCS.NS", "name": "Tata Consultancy Services"},
    {"symbol": "HDFCBANK", "yahoo_symbol": "HDFCBANK.NS", "name": "HDFC Bank"},
    {"symbol": "INFY", "yahoo_symbol": "INFY.NS", "name": "Infosys"},
    {"symbol": "ICICIBANK", "yahoo_symbol": "ICICIBANK.NS", "name": "ICICI Bank"},
    {"symbol": "HINDUNILVR", "yahoo_symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever"},
    {"symbol": "ITC", "yahoo_symbol": "ITC.NS", "name": "ITC Limited"},
    {"symbol": "SBIN", "yahoo_symbol": "SBIN.NS", "name": "State Bank of India"},
    {"symbol": "BHARTIARTL", "yahoo_symbol": "BHARTIARTL.NS", "name": "Bharti Airtel"},
    {"symbol": "KOTAKBANK", "yahoo_symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank"},
    {"symbol": "LT", "yahoo_symbol": "LT.NS", "name": "Larsen & Toubro"},
    {"symbol": "AXISBANK", "yahoo_symbol": "AXISBANK.NS", "name": "Axis Bank"},
    {"symbol": "BAJFINANCE", "yahoo_symbol": "BAJFINANCE.NS", "name": "Bajaj Finance"},
    {"symbol": "ASIANPAINT", "yahoo_symbol": "ASIANPAINT.NS", "name": "Asian Paints"},
    {"symbol": "MARUTI", "yahoo_symbol": "MARUTI.NS", "name": "Maruti Suzuki"},
    {"symbol": "HCLTECH", "yahoo_symbol": "HCLTECH.NS", "name": "HCL Technologies"},
    {"symbol": "SUNPHARMA", "yahoo_symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical"},
    {"symbol": "TITAN", "yahoo_symbol": "TITAN.NS", "name": "Titan Company"},
    {"symbol": "WIPRO", "yahoo_symbol": "WIPRO.NS", "name": "Wipro"},
    {"symbol": "ULTRACEMCO", "yahoo_symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement"},
    {"symbol": "NESTLEIND", "yahoo_symbol": "NESTLEIND.NS", "name": "Nestle India"},
    {"symbol": "POWERGRID", "yahoo_symbol": "POWERGRID.NS", "name": "Power Grid Corp"},
    {"symbol": "NTPC", "yahoo_symbol": "NTPC.NS", "name": "NTPC Limited"},
    {"symbol": "TATAMOTORS", "yahoo_symbol": "TATAMOTORS.NS", "name": "Tata Motors"},
    {"symbol": "M&M", "yahoo_symbol": "M&M.NS", "name": "Mahindra & Mahindra"},
    {"symbol": "BAJAJFINSV", "yahoo_symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv"},
    {"symbol": "ADANIENT", "yahoo_symbol": "ADANIENT.NS", "name": "Adani Enterprises"},
    {"symbol": "ADANIPORTS", "yahoo_symbol": "ADANIPORTS.NS", "name": "Adani Ports"},
    {"symbol": "COALINDIA", "yahoo_symbol": "COALINDIA.NS", "name": "Coal India"},
    {"symbol": "JSWSTEEL", "yahoo_symbol": "JSWSTEEL.NS", "name": "JSW Steel"},
    {"symbol": "TATASTEEL", "yahoo_symbol": "TATASTEEL.NS", "name": "Tata Steel"},
    {"symbol": "TECHM", "yahoo_symbol": "TECHM.NS", "name": "Tech Mahindra"},
    {"symbol": "INDUSINDBK", "yahoo_symbol": "INDUSINDBK.NS", "name": "IndusInd Bank"},
    {"symbol": "GRASIM", "yahoo_symbol": "GRASIM.NS", "name": "Grasim Industries"},
    {"symbol": "CIPLA", "yahoo_symbol": "CIPLA.NS", "name": "Cipla"},
    {"symbol": "DRREDDY", "yahoo_symbol": "DRREDDY.NS", "name": "Dr Reddy's Labs"},
    {"symbol": "EICHERMOT", "yahoo_symbol": "EICHERMOT.NS", "name": "Eicher Motors"},
    {"symbol": "APOLLOHOSP", "yahoo_symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals"},
    {"symbol": "DIVISLAB", "yahoo_symbol": "DIVISLAB.NS", "name": "Divi's Laboratories"},
    {"symbol": "HEROMOTOCO", "yahoo_symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp"},
    {"symbol": "BRITANNIA", "yahoo_symbol": "BRITANNIA.NS", "name": "Britannia Industries"},
    {"symbol": "HINDALCO", "yahoo_symbol": "HINDALCO.NS", "name": "Hindalco Industries"},
    {"symbol": "BPCL", "yahoo_symbol": "BPCL.NS", "name": "Bharat Petroleum"},
    {"symbol": "TATACONSUM", "yahoo_symbol": "TATACONSUM.NS", "name": "Tata Consumer Products"},
    {"symbol": "SBILIFE", "yahoo_symbol": "SBILIFE.NS", "name": "SBI Life Insurance"},
    {"symbol": "HDFCLIFE", "yahoo_symbol": "HDFCLIFE.NS", "name": "HDFC Life Insurance"},
    {"symbol": "PIDILITIND", "yahoo_symbol": "PIDILITIND.NS", "name": "Pidilite Industries"},
    {"symbol": "DABUR", "yahoo_symbol": "DABUR.NS", "name": "Dabur India"},
    {"symbol": "GODREJCP", "yahoo_symbol": "GODREJCP.NS", "name": "Godrej Consumer"},
    {"symbol": "MARICO", "yahoo_symbol": "MARICO.NS", "name": "Marico"},
    {"symbol": "BERGEPAINT", "yahoo_symbol": "BERGEPAINT.NS", "name": "Berger Paints"},
    {"symbol": "COLPAL", "yahoo_symbol": "COLPAL.NS", "name": "Colgate-Palmolive India"},
    {"symbol": "HAVELLS", "yahoo_symbol": "HAVELLS.NS", "name": "Havells India"},
    {"symbol": "VOLTAS", "yahoo_symbol": "VOLTAS.NS", "name": "Voltas"},
    {"symbol": "SIEMENS", "yahoo_symbol": "SIEMENS.NS", "name": "Siemens India"},
    {"symbol": "ABB", "yahoo_symbol": "ABB.NS", "name": "ABB India"},
    {"symbol": "BOSCHLTD", "yahoo_symbol": "BOSCHLTD.NS", "name": "Bosch Limited"},
    {"symbol": "SHREECEM", "yahoo_symbol": "SHREECEM.NS", "name": "Shree Cement"},
    {"symbol": "AMBUJACEM", "yahoo_symbol": "AMBUJACEM.NS", "name": "Ambuja Cements"},
    {"symbol": "ACC", "yahoo_symbol": "ACC.NS", "name": "ACC Limited"},
    {"symbol": "DLF", "yahoo_symbol": "DLF.NS", "name": "DLF Limited"},
    {"symbol": "GAIL", "yahoo_symbol": "GAIL.NS", "name": "GAIL India"},
    {"symbol": "IOC", "yahoo_symbol": "IOC.NS", "name": "Indian Oil Corporation"},
    {"symbol": "ONGC", "yahoo_symbol": "ONGC.NS", "name": "Oil & Natural Gas Corp"},
    {"symbol": "BEL", "yahoo_symbol": "BEL.NS", "name": "Bharat Electronics"},
    {"symbol": "HAL", "yahoo_symbol": "HAL.NS", "name": "Hindustan Aeronautics"},
    {"symbol": "BHEL", "yahoo_symbol": "BHEL.NS", "name": "Bharat Heavy Electricals"},
    {"symbol": "IRCTC", "yahoo_symbol": "IRCTC.NS", "name": "Indian Railway Catering"},
    {"symbol": "ZOMATO", "yahoo_symbol": "ZOMATO.NS", "name": "Zomato"},
    {"symbol": "PAYTM", "yahoo_symbol": "PAYTM.NS", "name": "Paytm"},
    {"symbol": "NYKAA", "yahoo_symbol": "NYKAA.NS", "name": "FSN E-Commerce (Nykaa)"},
    {"symbol": "POLICYBZR", "yahoo_symbol": "POLICYBZR.NS", "name": "PB Fintech"},
    {"symbol": "DMART", "yahoo_symbol": "DMART.NS", "name": "Avenue Supermarts"},
    {"symbol": "TRENT", "yahoo_symbol": "TRENT.NS", "name": "Trent Limited"},
    {"symbol": "JINDALSTEL", "yahoo_symbol": "JINDALSTEL.NS", "name": "Jindal Steel & Power"},
    {"symbol": "SAIL", "yahoo_symbol": "SAIL.NS", "name": "Steel Authority of India"},
    {"symbol": "NMDC", "yahoo_symbol": "NMDC.NS", "name": "NMDC Limited"},
    {"symbol": "VEDL", "yahoo_symbol": "VEDL.NS", "name": "Vedanta Limited"},
    {"symbol": "HINDZINC", "yahoo_symbol": "HINDZINC.NS", "name": "Hindustan Zinc"},
    {"symbol": "NATIONALUM", "yahoo_symbol": "NATIONALUM.NS", "name": "National Aluminium"},
    {"symbol": "BANKBARODA", "yahoo_symbol": "BANKBARODA.NS", "name": "Bank of Baroda"},
    {"symbol": "PNB", "yahoo_symbol": "PNB.NS", "name": "Punjab National Bank"},
    {"symbol": "CANBK", "yahoo_symbol": "CANBK.NS", "name": "Canara Bank"},
    {"symbol": "UNIONBANK", "yahoo_symbol": "UNIONBANK.NS", "name": "Union Bank of India"},
    {"symbol": "IDFCFIRSTB", "yahoo_symbol": "IDFCFIRSTB.NS", "name": "IDFC First Bank"},
    {"symbol": "FEDERALBNK", "yahoo_symbol": "FEDERALBNK.NS", "name": "Federal Bank"},
    {"symbol": "AUBANK", "yahoo_symbol": "AUBANK.NS", "name": "AU Small Finance Bank"},
    {"symbol": "BANDHANBNK", "yahoo_symbol": "BANDHANBNK.NS", "name": "Bandhan Bank"},
    {"symbol": "LICHSGFIN", "yahoo_symbol": "LICHSGFIN.NS", "name": "LIC Housing Finance"},
    {"symbol": "MUTHOOTFIN", "yahoo_symbol": "MUTHOOTFIN.NS", "name": "Muthoot Finance"},
    {"symbol": "CHOLAFIN", "yahoo_symbol": "CHOLAFIN.NS", "name": "Cholamandalam Investment"},
    {"symbol": "SHRIRAMFIN", "yahoo_symbol": "SHRIRAMFIN.NS", "name": "Shriram Finance"},
    {"symbol": "LTF", "yahoo_symbol": "LTF.NS", "name": "L&T Finance"},
    {"symbol": "PFC", "yahoo_symbol": "PFC.NS", "name": "Power Finance Corporation"},
    {"symbol": "RECLTD", "yahoo_symbol": "RECLTD.NS", "name": "REC Limited"},
    {"symbol": "IRFC", "yahoo_symbol": "IRFC.NS", "name": "Indian Railway Finance"},
    {"symbol": "TORNTPHARM", "yahoo_symbol": "TORNTPHARM.NS", "name": "Torrent Pharmaceuticals"},
    {"symbol": "LUPIN", "yahoo_symbol": "LUPIN.NS", "name": "Lupin Limited"},
    {"symbol": "BIOCON", "yahoo_symbol": "BIOCON.NS", "name": "Biocon Limited"},
    {"symbol": "AUROPHARMA", "yahoo_symbol": "AUROPHARMA.NS", "name": "Aurobindo Pharma"},
    {"symbol": "GLENMARK", "yahoo_symbol": "GLENMARK.NS", "name": "Glenmark Pharmaceuticals"},
    {"symbol": "ALKEM", "yahoo_symbol": "ALKEM.NS", "name": "Alkem Laboratories"},
    {"symbol": "MRF", "yahoo_symbol": "MRF.NS", "name": "MRF Limited"},
    {"symbol": "BALKRISIND", "yahoo_symbol": "BALKRISIND.NS", "name": "Balkrishna Industries"},
    {"symbol": "EXIDEIND", "yahoo_symbol": "EXIDEIND.NS", "name": "Exide Industries"},
    {"symbol": "CUMMINSIND", "yahoo_symbol": "CUMMINSIND.NS", "name": "Cummins India"},
    {"symbol": "ASTRAL", "yahoo_symbol": "ASTRAL.NS", "name": "Astral Limited"},
    {"symbol": "SUPREMEIND", "yahoo_symbol": "SUPREMEIND.NS", "name": "Supreme Industries"},
    {"symbol": "POLYCAB", "yahoo_symbol": "POLYCAB.NS", "name": "Polycab India"},
    {"symbol": "KEI", "yahoo_symbol": "KEI.NS", "name": "KEI Industries"},
    {"symbol": "PERSISTENT", "yahoo_symbol": "PERSISTENT.NS", "name": "Persistent Systems"},
    {"symbol": "COFORGE", "yahoo_symbol": "COFORGE.NS", "name": "Coforge Limited"},
    {"symbol": "MPHASIS", "yahoo_symbol": "MPHASIS.NS", "name": "Mphasis Limited"},
    {"symbol": "LTIM", "yahoo_symbol": "LTIM.NS", "name": "LTIMindtree"},
    {"symbol": "OFSS", "yahoo_symbol": "OFSS.NS", "name": "Oracle Financial Services"},
]

BENCHMARKS = [
    {"name": "NIFTY50", "yahoo_symbol": "^NSEI"},
]
